//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologicalPracticeApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Ecolabel = new HashSet<Ecolabel>();
        }
    
        public int Id { get; set; }

        //[Required]
        //[StringLength(25, ErrorMessage = "Длина введенных Вами данных в поле превышают макимальную допустимую длину")]
        public string Name { get; set; }

        //[Required]
        //[StringLength(25, ErrorMessage = "Длина введенных Вами данных в поле превышают макимальную допустимую длину")]
        public string Address { get; set; }

        //[Required]
        //[Phone(ErrorMessage = "Неверный ввод номера телефона")]
        public string PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ecolabel> Ecolabel { get; set; }
    }
}
