//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologicalPracticeApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ecolabel> EcolabelSet { get; set; }
        public virtual DbSet<Company> CompanySet { get; set; }
        public virtual DbSet<Country> CountrySet { get; set; }
        public virtual DbSet<Country_Ecolabel> Country_EcolabelSet { get; set; }
        public virtual DbSet<EcoType> EcoTypeSet { get; set; }
        public virtual DbSet<EcoType_Ecolabel> EcoType_EcolabelSet { get; set; }
        public virtual DbSet<Demand> DemandSet { get; set; }
        public virtual DbSet<Demand_Ecolabel> Demand_EcolabelSet { get; set; }
        public virtual DbSet<PersonalCabinet> PersonalCabinetSet { get; set; }
        public virtual DbSet<Person> PersonSet { get; set; }
        public virtual DbSet<AccessLevel> AccessLevelSet { get; set; }
    }
}
