//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologicalPracticeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalCabinet
    {
        public int Id { get; set; }
        public int Mark { get; set; }
        public int EcolabelID { get; set; }
        public int PersonID { get; set; }
    
        public virtual Ecolabel Ecolabel { get; set; }
        public virtual Person Person { get; set; }
    }
}
